library(stats)
library(Rcpp)
library(RcppArmadillo)

sourceCpp("gibbsSampler.cpp")

# don't include compilation time
start_time <- Sys.time()

## This is an example script currently.

# TODO: 1) turn this into a function that can be exported
# 2) add Rcpp function
# 3) allow for more general mixture components

## Unlike R, elements need to be zero based for C++
vocab = c(0,1,2,3,4)
lengthVocab <- length(vocab)
numTopics <- 2
numDocuments <- 32
lengthDocuments <- 24
numWords <- numDocuments*lengthDocuments
topics <- 0:(numTopics-1)

alphaWords = 0.2
alphaTopics = 0.2

# initialize word distributions
z1 <- c(17/30,1/3,1/10,0,0)
z2 <- c(0,0,1/10,1/3,17/30)
wordDistributions <- rbind(z1,z2)
generatedTopics <- rep(NA, numDocuments)

docIDs <- c()
words <- c()
currentTopic <- 0

## Assume for now that documents only have one mixture component
## Meaning each document is generated by exactly one topic
## TODO Generalize this to mixtures of topics

for (i in 1:numDocuments) {
  docIDs <- c(docIDs, rep(i - 1, lengthDocuments))
  z = sample(topics, 1)
  generatedTopics[i] <- z
  dist <- wordDistributions[z+1,]
  sampledWords <- sample(vocab, lengthDocuments, replace = TRUE, prob = dist)
  words <- c(words, sampledWords)
}


posteriorSamples <- gibbsSampler(words = words,
                                 docIDs = docIDs,
                                 topics = topics,
                                 lengthVocab = lengthVocab,
                                 numDocuments = numDocuments,
                                 alphaWords = alphaWords,
                                 alphaTopics = alphaTopics,
                                 numEpochs = 50000,
                                 warmUp = 5000,
                                 lag = 50)


# Obtain posterior means
posteriorAlphaWords <- Reduce("+", posteriorSamples[[1]])/length(posteriorSamples[[1]])
posteriorAlphaTopics <- Reduce("+", posteriorSamples[[2]])/length(posteriorSamples[[2]])
print(posteriorAlphaWords)
print(posteriorAlphaTopics)

end_time <- Sys.time()

print(paste0("running  time: ", end_time - start_time))





