library(stats)
library(Rcpp)
library(RcppArmadillo)
library(tictoc)
library(topicmodels)
library(tidyverse)
library(tidytext)

sourceCpp("viAlgorithm.cpp")
# source("R/data_gen.R")
# source("R/assessments.R")

# don't include compilation time
start_time <- Sys.time()

## This is an example script currently.

# TODO: 1) turn this into a function that can be exported
# 2) add Rcpp function
# 3) allow for more general mixture components

## Unlike R, elements need to be zero based for C++
set.seed(19890418)
vocab = c(0,1,2,3,4,5)
lengthVocab <- length(vocab)
numTopics <- 3
numDocuments <- 32
lengthDocuments <- 24
numWords <- numDocuments*lengthDocuments
topics <- 0:(numTopics-1)

alphaWords = 0.2
alphaTopics = 0.2

# initialize word distributions
z1 <- c(1/2,1/3,1/6,0,0,0)
z2 <- c(0,0,1/2,1/3,1/6,0)
z3 <- c(1/6,0,0,0,1/2,1/3)
wordDistributions <- rbind(z1,z2,z3)
generatedTopics <- rep(NA, numDocuments)

docIDs <- c()
words <- c()
currentTopic <- 0

## Assume for now that documents only have one mixture component
## Meaning each document is generated by exactly one topic
## TODO Generalize this to mixtures of topics

for (i in 1:numDocuments) {
  docIDs <- c(docIDs, rep(i - 1, lengthDocuments))
  z = sample(topics, 1)
  generatedTopics[i] <- z
  dist <- wordDistributions[z+1,]
  sampledWords <- sample(vocab, lengthDocuments, replace = TRUE, prob = dist)
  words <- c(words, sampledWords)
}

dat = data.frame("doc"=docIDs,"word"=words)
dat = data.frame(data.table::as.data.table(dat)[, .N, by = c('doc','word')])

tic()
resList <- svi(data=as.matrix(dat),
               numDistinctWordVec=as.vector(table(dat$doc)),
               topics = topics,
               lengthVocab = lengthVocab,
               numDocuments = numDocuments,
               maxIterConst = 16,
               maxVBiterConst = 16,
               alphaWords = alphaWords,
               alphaTopics = alphaTopics,
               rho = 0.1,
               tol = 0.0001)
toc()

true = generatedTopics+1
pred = get_plurarity_topics(resList[[3]])
get_best_mapping(pred,true)$prop_correct
#
# print(resList[[1]])
# print(resList[[3]])
# print("printing true values")
# print(wordDistributions)
# print(generatedTopics)
#
#
# dat_matrix = data.frame(dat) %>% cast_dtm(doc,word,N)
#
# tic()
# mod = topicmodels::LDA(dat_matrix,k = 3, method = "VEM")
# tm_res = posterior(mod,dat_matrix)
# toc()
# true = generatedTopics+1
# pred = get_plurarity_topics(tm_res$topics)
# get_best_mapping(pred,true)$prop_correct
#
# load("data_file_d500_v100_t2.Rda")
# dat_matrix = data.frame(data_obj$dat) %>% cast_dtm(doc,word,N)
# tic()
# mod = topicmodels::LDA(dat_matrix,k = 2, method = "VEM")
# tm_res = posterior(mod,dat_matrix)
# toc()
# true = data_obj$gen_topics+1
# pred = get_plurarity_topics(tm_res$topics)
# get_best_mapping(pred,true)
#
# tic()
# resList <- svi(data=as.matrix(data_obj$dat),
#                numDistinctWordVec=as.vector(table(data_obj$dat$doc)),
#                topics = 0:(2-1),
#                lengthVocab = 100,
#                numDocuments = 500,
#                maxIterConst = 1000,
#                maxVBiterConst = 1000,
#                alphaWords = alphaWords,
#                alphaTopics = alphaTopics,
#                rho = 0.3,
#                tol = 0.01)
# toc()
# true = data_obj$gen_topics+1
# pred = get_plurarity_topics(resList[[3]])
# get_best_mapping(pred,true)$prop_correct



