library(stats)
library(Rcpp)
library(RcppArmadillo)
library(tictoc)
library(gtools)

vocab = c(0,1,2,3,4,5)
lengthVocab <- length(vocab)
numTopics <- 3
numDocuments <- 32
lengthDocuments <- 24
numWords <- numDocuments*lengthDocuments
topics <- 0:(numTopics-1)

alphaWords = 0.2
alphaTopics = 0.2

# initialize word distributions
z1 <- c(1/2,1/3,1/6,0,0,0)
z2 <- c(0,0,1/2,1/3,1/6,0)
z3 <- c(1/6,0,0,0,1/2,1/3)
wordDistributions <- rbind(z1,z2,z3)
generatedTopics <- rep(NA, numDocuments)

docIDs <- c()
words <- c()
currentTopic <- 0

## Assume for now that documents only have one mixture component
## Meaning each document is generated by exactly one topic
## TODO Generalize this to mixtures of topics

for (i in 1:numDocuments) {
  docIDs <- c(docIDs, rep(i - 1, lengthDocuments))
  z = sample(topics, 1)
  generatedTopics[i] <- z
  dist <- wordDistributions[z+1,]
  sampledWords <- sample(vocab, lengthDocuments, replace = TRUE, prob = dist)
  words <- c(words, sampledWords)
}

sourceCpp("viAlgorithm.cpp")

tic()
resList <- svi(words = words,
               docIDs = docIDs,
               lengthDocumentVec = rep(lengthDocuments,numDocuments),
               topics = topics,
               lengthVocab = lengthVocab,
               numDocuments = numDocuments,
               maxIterConst = 100,
               maxVBiterConst = 100,
               alphaWords = alphaWords,
               alphaTopics = alphaTopics,
               rho = 0.1,
               tol = 0.0001)
toc()
print("printing estimated variational parameters for the word distribution")
print(resList[[1]])
print("printing estimated variational parameters for the topic distribution")
print(resList[[3]])

print("printing true values")
print(wordDistributions)
print(generatedTopics)


map_pred <- function(mapping,pred){
  mapped_predict = rep(NA,length(predict))
  for(i in 1:length(mapping)){
    j = mapping[i]
    mapped_predict[pred == i] = j
  }
  return(mapped_predict)
}
prop_correctly_classified <- function(mapping,predict,true_val){
  mapped_predict = map_pred(mapping,predict)
  correct = 0
  for(i in 1:length(true_val)){
    if(true_val[i]==mapped_predict[i]){
      correct = correct+1
    }
  }
  return(correct/length(true_val))
}

# get the 1-indexed topics by plurarity of the document to topic matrix
get_plurarity_topics <- function(doc_2_top_mat){
  return(apply(resList[[3]],1,FUN=which.max))
}



all_mappings = permutations(n = numTopics, r = numTopics, v = 1:numTopics)

results = apply(all_mappings,1,FUN = function(perm){prop_correctly_classified(perm,pred,true)})

get_best_mapping <- function(predicted,true){
  K = max(true)
  all_mappings = permutations(n = K, r = K, v = 1:K)
  results = apply(all_mappings,1,FUN = function(perm){prop_correctly_classified(perm,predicted,true)})
  max_i = which.max(results)
  return(list("prop_correct"=results[max_i],"mapped_pred"=map_pred(all_mappings[max_i,],predicted),"true_val"=true,"mapping"=all_mappings[max_i,]))
}

true = generatedTopics+1
pred = get_plurarity_topics(resList[[3]])
get_best_mapping(pred,true)
