# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsSampler <- function(words, docIDs, topics, lengthVocab, numDocuments, alphaWords, alphaTopics, numEpochs, warmUp, lag) {
    .Call(`_viLDA_gibbsSampler`, words, docIDs, topics, lengthVocab, numDocuments, alphaWords, alphaTopics, numEpochs, warmUp, lag)
}

rcpparma_hello_world <- function() {
    .Call(`_viLDA_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_viLDA_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_viLDA_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_viLDA_rcpparma_bothproducts`, x)
}

svi <- function(data, numDistinctWordVec, topics, lengthVocab, numDocuments, maxIterConst, maxVBiterConst, alphaWords, alphaTopics, rho, tol) {
    .Call(`_viLDA_svi`, data, numDistinctWordVec, topics, lengthVocab, numDocuments, maxIterConst, maxVBiterConst, alphaWords, alphaTopics, rho, tol)
}

