# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbsSampler <- function(words, docIDs, topics, lengthVocab, numDocuments, alphaWords, alphaTopics, numEpochs, warmUp, lag) {
    .Call(`_viLDA_gibbsSampler`, words, docIDs, topics, lengthVocab, numDocuments, alphaWords, alphaTopics, numEpochs, warmUp, lag)
}

svi <- function(data, numDistinctWordVec, topics, lengthVocab, numDocuments, maxIterConst, maxVBiterConst, alphaWords, alphaTopics, rho, tol) {
    .Call(`_viLDA_svi`, data, numDistinctWordVec, topics, lengthVocab, numDocuments, maxIterConst, maxVBiterConst, alphaWords, alphaTopics, rho, tol)
}

