library(stats)
library(Rcpp)
library(RcppArmadillo)
# load required libraries

# TODO: update the cpp code to be less NLP and more bio focused
sourceCpp("gibbsSampler.cpp")
# load the cpp implementation of the alg

#' viLDA.gibbs
#'
#' TODO: fill out later
#'
#' @export
viLDA.gibbs <- function(N,K,p,data,alpha,beta,seed=19890419,...){
  set.seed(seed)
  data.long = c(t(data))
  data.id = c(sapply(1:N,FUN=function(i){rep(i - 1, p)}))
  posteriorSamples <- gibbsSampler(words = data.long,
                                   docIDs = docIDs,
                                   topics = 0:(K-1),
                                   lengthVocab = p,
                                   numDocuments = N,
                                   alphaWords = beta,
                                   alphaTopics = alpha,
                                   numEpochs = 50000,
                                   warmUp = 5000,
                                   lag = 50)


  # Obtain posterior means
  posteriorAlphaWords <- Reduce("+", posteriorSamples[[1]])/length(posteriorSamples[[1]])
  posteriorAlphaTopics <- Reduce("+", posteriorSamples[[2]])/length(posteriorSamples[[2]])
  result <- list("posterior_gene_to_cluster"=posteriorAlphaWords,
                 "posterior_cell_to_cluster"=posteriorAlphaTopics,
                 "posterior_samples"=posteriorSamples)
  return(result)
}

viLDA.gibbs.test <- function(){
  vocab = c(0,1,2,3,4)
  lengthVocab <- length(vocab)
  numTopics <- 2
  numDocuments <- 32
  lengthDocuments <- 24
  numWords <- numDocuments*lengthDocuments
  topics <- 0:(numTopics-1)

  alphaWords = 0.2
  alphaTopics = 0.2

  # initialize word distributions
  z1 <- c(17/30,1/3,1/10,0,0)
  z2 <- c(0,0,1/10,1/3,17/30)
  wordDistributions <- rbind(z1,z2)
  generatedTopics <- rep(NA, numDocuments)

  docIDs <- c()
  words <- c()
  currentTopic <- 0

  ## Assume for now that documents only have one mixture component
  ## Meaning each document is generated by exactly one topic
  ## TODO Generalize this to mixtures of topics

  for (i in 1:numDocuments) {
    docIDs <- c(docIDs, rep(i - 1, lengthDocuments))
    z = sample(topics, 1)
    generatedTopics[i] <- z
    dist <- wordDistributions[z+1,]
    sampledWords <- sample(vocab, lengthDocuments, replace = TRUE, prob = dist)
    words <- c(words, sampledWords)
  }
  data = matrix(words,nrow=numDocuments)
  out <- viLDA.gibbs(N=numDocuments,K=numTopics,p=lengthDocuments,data=data,alpha=alphaTopics,beta=alphaWords)
  print(out)
}
